#undef B_TRANSLATION_CONTEXT
#define B_TRANSLATION_CONTEXT "KeyboardLayoutNames"
B_TRANSLATE_MARK_VOID("Fizzbook NL2")
B_TRANSLATE_MARK_VOID("Generic 104-key")
B_TRANSLATE_MARK_VOID("Generic 105-key International")
B_TRANSLATE_MARK_VOID("Kinesis Advantage")
B_TRANSLATE_MARK_VOID("Kinesis Ergo Elan International")
B_TRANSLATE_MARK_VOID("TypeMatrix 2030")
B_TRANSLATE_MARK_VOID("X-Bows Nature")
B_TRANSLATE_MARK_VOID("Apple\ Aluminum")
B_TRANSLATE_MARK_VOID("Apple Aluminium Extended International")
B_TRANSLATE_MARK_VOID("Apple Aluminium International")
B_TRANSLATE_MARK_VOID("Apple Aluminum (US)")
B_TRANSLATE_MARK_VOID("Apple Aluminum Extended (US)")
B_TRANSLATE_MARK_VOID("ThinkPad")
B_TRANSLATE_MARK_VOID("ThinkPad (US)")
B_TRANSLATE_MARK_VOID("ThinkPad International")
B_TRANSLATE_MARK_VOID("ThinkPad T400s (US)")
B_TRANSLATE_MARK_VOID("ThinkPad T400s International")
B_TRANSLATE_MARK_VOID("ThinkPad X1 (US)")
B_TRANSLATE_MARK_VOID("ThinkPad X1 International")
B_TRANSLATE_MARK_VOID("ThinkPad X100e (US)")
B_TRANSLATE_MARK_VOID("ThinkPad X100e International")
