app_name = 'Sudoku'
linux_desktop_id = 'x-vnd.Haiku-Sudoku'
linux_desktop_categories = 'Game;LogicGame;'

app_srcs = files(
    'ProgressWindow.cpp',
    'Sudoku.cpp',
    'SudokuField.cpp',
    'SudokuGenerator.cpp',
    'SudokuView.cpp',
    'SudokuWindow.cpp',
    'SudokuSolver.cpp',
)


app_resource_defs = files(
    app_name + '.rdef'
)

app_dependencies = [dep_libbe, dep_libtracker]
