# To test this ci build locally:
#
# sudo docker run --rm -v "$PWD":/workspace -w /workspace registry.fedoraproject.org/fedora:44 sh -lc '
#  set -e
#  dnf install -y gcc gcc-c++ clang meson ninja-build pkgconf-pkg-config flex bison cairo-devel libpng-devel libjpeg-turbo-devel libwebp-devel zlib-devel openssl-devel libicu-devel freetype-devel pango-devel pixman-devel fontconfig-devel glib2-devel libX11-devel libX11-xcb libXcursor-devel libXrandr-devel libxkbcommon-devel libxkbcommon-x11-devel wayland-devel cppunit-devel
#  rm -rf builddir-docker-ci
#  meson setup builddir-docker-ci
#  ninja -C builddir-docker-ci
# '

image: registry.fedoraproject.org/fedora:44

stages:
  - build
  - test

before_script:
  - dnf install -y
      gcc gcc-c++ clang
      meson ninja-build pkgconf-pkg-config
      flex bison
      cairo-devel libpng-devel libjpeg-turbo-devel libwebp-devel zlib-devel
      openssl-devel
      libicu-devel freetype-devel pango-devel
      pixman-devel fontconfig-devel glib2-devel
      libX11-devel libX11-xcb libXcursor-devel libXrandr-devel
      libxkbcommon-devel libxkbcommon-x11-devel
      wayland-devel
      cppunit-devel

build:
  stage: build
  script:
    - meson setup builddir
    - ninja -C builddir
  artifacts:
    when: always
    paths:
      - builddir

kernel_tests:
  stage: test
  script:
    - ./run_kernel_tests.sh
  dependencies:
    - build

unit_tests:
  allow_failure: true
  stage: test
  script:
    - ./run_unit_tests.sh
  dependencies:
    - build
