#!/bin/sh

#./configure --enable-sdl && make deps && make
#./configure --prefix=/usr/local/ --enable-sdl CC="gcc -m32" CXX="g++ -m32" LD="ld -m32" && make deps && make -j5
./configure --prefix=/usr/local/ --enable-sdl && make deps && make -j5

