# Unfortunately, ~ is not supported in ini files, full path is needed
# Change as needed to support your MXE installation location

[binaries]
c = '/home/billh/mxe/usr/bin/x86_64-w64-mingw32.shared-gcc'
cpp = '/home/billh/mxe/usr/bin/x86_64-w64-mingw32.shared-g++'
ar = '/home/billh/mxe/usr/bin/x86_64-w64-mingw32.shared-ar'
strip = '/home/billh/mxe/usr/bin/x86_64-w64-mingw32.shared-strip'
pkgconfig = '/home/billh/mxe/usr/bin/x86_64-w64-mingw32.shared-pkg-config'
windres = '/home/billh/mxe/usr/bin/x86_64-w64-mingw32.shared-windres'
# Native tools (run on build machine during cross-compilation)
rc = '/usr/local/bin/rc'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
# MXE sysroot
sys_root = '/home/billh/mxe/usr/x86_64-w64-mingw32.shared'

# Tell pkg-config where to find .pc files
pkg_config_libdir = '/home/billh/mxe/usr/x86_64-w64-mingw32.shared/lib/pkgconfig'
pkg_config_path = '/home/billh/mxe/usr/x86_64-w64-mingw32.shared/lib/pkgconfig'

# Avoid Meson using the native pkg-config for host
native_pkg_config = false
