[binaries]
c = '~/mxe/usr/bin/x86_64-w64-mingw32.shared-gcc'
cpp = '~/mxe/usr/bin/x86_64-w64-mingw32.shared-g++'
ar = '~/mxe/usr/bin/x86_64-w64-mingw32.shared-ar'
strip = '~/mxe/usr/bin/x86_64-w64-mingw32.shared-strip'
pkgconfig = '~/mxe/usr/bin/x86_64-w64-mingw32.shared-pkg-config'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
# MXE sysroot
sys_root = '~/mxe/usr/x86_64-w64-mingw32.shared'

# Tell pkg-config where to find .pc files
pkg_config_libdir = '~/mxe/usr/x86_64-w64-mingw32.shared/lib/pkgconfig'
pkg_config_path = '~/mxe/usr/x86_64-w64-mingw32.shared/lib/pkgconfig'

# Avoid Meson using the native pkg-config for host
native_pkg_config = false
