# Recursively build the Cosmoe source tree
# Copyright 2002-2024, Bill Hayden

ROOT_DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))


all:
	@for subproj in $(SUBPROJECTS); do\
		if ! $(MAKE) -C $(CURDIR)/$$subproj; then exit 1; fi;\
	done
	#$(MAKE) -C $(ROOT_DIR)src/kits addresources
	#$(MAKE) -C $(ROOT_DIR)src/kits/tracker addresources

doc:
	@for subproj in $(SUBPROJECTS); do\
		if ! $(MAKE) -C $(CURDIR)/$$subproj doc; then exit 1; fi;\
	done

install-doc:
	@for subproj in $(SUBPROJECTS); do\
		if ! $(MAKE) -C $(CURDIR)/$$subproj install-doc; then exit 1; fi;\
	done

install:
	@for subproj in $(SUBPROJECTS); do\
		if ! $(MAKE) -C $(CURDIR)/$$subproj install; then exit 1; fi;\
	done

clean:
	@for subproj in $(SUBPROJECTS); do\
		if ! $(MAKE) -C $(CURDIR)/$$subproj clean; then exit 1; fi;\
	done

distclean:
	@for subproj in $(SUBPROJECTS); do\
		if ! $(MAKE) -C $(CURDIR)/$$subproj distclean; then exit 1; fi;\
	done
	-rm -f Makefile
	-rm -f config.cache
	-rm -f config.log
	-rm -f config.status
	-rm -f config.h
	-rm -f *.out
	-rm -f *~
	-rm -f core.*
	-rm -rf autom4te*
	-rm -f cosmoe.specs

deps:
	@for subproj in $(SUBPROJECTS); do\
		$(MAKE) -ik -C $(CURDIR)/$$subproj deps 2>/dev/null;\
	done
