# Options for enabling/disabling backends
option('enable_wayland_backend',
  type : 'boolean',
  value : true,
  description : 'Enable Wayland backend')

option('enable_x11_backend',
  type : 'boolean',
  value : true,
  description : 'Enable X11 backend')

option('enable_unit_test_compile',
  type : 'boolean',
  value : true,
  description : 'Enable compilation of unit tests')

option('enable_libgame',
  type : 'boolean',
  value : true,
  description : 'Build Game Kit as standalone libgame')

option('native_rc_path',
  type : 'string',
  value : '',
  description : 'Path to the native rc tool to use for cross-compiling resources')
