srcs_app = [
    'AppDefs.cpp',
    'Application.cpp',
    'AppMisc.cpp',
    # 'AppServerLink.cpp',
    'Clipboard.cpp',
    'Cursor.cpp',
    # 'DesktopLink.cpp',
    'DirectMessageTarget.cpp',
    'Handler.cpp',
    'InitTerminateLibBe.cpp',
    'Invoker.cpp',
    # 'LaunchRoster.cpp',
    # 'LinkReceiver.cpp',
    # 'LinkSender.cpp',
    'Looper.cpp',
    'LooperList.cpp',
    'MessageAdapter.cpp',
    'Message.cpp',
    'MessageFilter.cpp',
    'MessageQueue.cpp',
    'MessageRunner.cpp',
    'MessageUtils.cpp',
    'Messenger.cpp',
    # 'PortLink.cpp',
    'PropertyInfo.cpp',
    'RegistrarDefs.cpp',
    # 'Roster.cpp',
    # # 'RosterPrivate.cpp',
    # 'Server.cpp',
    # 'ServerLink.cpp',
    'ServerMemoryAllocator.cpp',
    'TokenSpace.cpp',
    'TypeConstants.cpp',
]

srcs_app = files(srcs_app)