srcs_interface = [
			'AboutWindow.cpp',
			'AbstractLayout.cpp',
			'AbstractLayoutItem.cpp',
			'AbstractSpinner.cpp',
			'AffineTransform.cpp',
			'Alert.cpp',
			'Alignment.cpp',
			'Bitmap.cpp',
			'BMCPrivate.cpp',
			'Box.cpp',
			'Button.cpp',
			'CardLayout.cpp',
			'CardView.cpp',
			'ChannelControl.cpp',
			'ChannelSlider.cpp',
			'CheckBox.cpp',
			'ColorConversion.cpp',
			'ColorControl.cpp',
			'ColorMenuItem.cpp',
			'ColumnListView.cpp',
			'ColumnTypes.cpp',
			'Control.cpp',
			'ControlLook.cpp',
			'CosmoeBackendAPI.cpp',
			'CosmoeBackendFactory.cpp',
			# 'DecorInfo.cpp',
			#'Deskbar.cpp',
			'DecimalSpinner.cpp',
			'DisplayScaleManager.cpp',
			'Dragger.cpp',
			'Font.cpp',
			'Gradient.cpp',
			'GradientLinear.cpp',
			'GradientRadial.cpp',
			# 'GradientRadialFocus.cpp',
			# 'GradientDiamond.cpp',
			# 'GradientConic.cpp',
			'GraphicsDefs.cpp',
			'GridLayout.cpp',
			'GridLayoutBuilder.cpp',
			'GridView.cpp',
			'GroupLayout.cpp',
			'GroupLayoutBuilder.cpp',
			'GroupView.cpp',
			'HaikuControlLook.cpp',
			'Icon.cpp',
			'Input.cpp',
			'InterfaceDefs.cpp',
			'Layout.cpp',
			'LayoutContext.cpp',
			'LayoutItem.cpp',
			'LayoutUtils.cpp',
			'ListItem.cpp',
			'ListView.cpp',
			'Menu.cpp',
			'MenuBar.cpp',
			'MenuField.cpp',
			'MenuItem.cpp',
			'MenuItemPrivate.cpp',
			'MenuPrivate.cpp',
			'MenuWindow.cpp',
			'OptionControl.cpp',
			'OptionPopUp.cpp',
			'OutlineListView.cpp',
			# 'Picture.cpp',
			# 'PictureButton.cpp',
			# 'PictureDataWriter.cpp',
			# 'PicturePlayer.cpp',
			'Point.cpp',
			'Polygon.cpp',
			'PopUpMenu.cpp',
			# 'PrintJob.cpp',
			# 'PrivateScreen.cpp',
			'RadioButton.cpp',
			'Rect.cpp',
			'Region.cpp',
			'RegionSupport.cpp',
			'Screen.cpp',
			'ScrollBar.cpp',
			'ScrollView.cpp',
			'SeparatorItem.cpp',
			'SeparatorView.cpp',
			'Shape.cpp',
			'Shelf.cpp',
			'Size.cpp',
			'Slider.cpp',
			'SpaceLayoutItem.cpp',
			'Spinner.cpp',
			'SplitLayout.cpp',
			'SplitLayoutBuilder.cpp',
			'SplitView.cpp',
			'StatusBar.cpp',
			'StringItem.cpp',
			'StringView.cpp',
			'TabView.cpp',
			'TextControl.cpp',
			'TextInput.cpp',
			'TextView.cpp',
			'ToolTip.cpp',
			'ToolTipManager.cpp',
			'TwoDimensionalLayout.cpp',
			'View.cpp',
			'ViewLayoutItem.cpp',
			'Window.cpp',
			'ZombieReplicantView.cpp',

			# BTextView support'
			'textview_support/InlineInput.cpp',
			'textview_support/LineBuffer.cpp',
			'textview_support/StyleBuffer.cpp',
			'textview_support/TextGapBuffer.cpp',
			'textview_support/UndoBuffer.cpp',
			'textview_support/WidthBuffer.cpp',

			# layouter
			'layouter/CollapsingLayouter.cpp',
			'layouter/ComplexLayouter.cpp',
			'layouter/Layouter.cpp',
			'layouter/LayoutOptimizer.cpp',
			'layouter/OneElementLayouter.cpp',
			'layouter/SimpleLayouter.cpp',
]

srcs_interface = files(srcs_interface)