srcs_storage = [
    'AppFileInfo.cpp',
    'Directory.cpp',
    'DriverSettings.cpp',
    'Entry.cpp',
    'EntryList.cpp',
    # 'EntryOperationEngineBase.cpp',
    # 'FdIO.cpp',
    'File.cpp',
    # 'FileDescriptorIO.cpp',
    # 'FileIO.cpp',
    'FindDirectory.cpp',
    'kernel_interface.POSIX.cpp',
    'MergedDirectory.cpp',
    'Mime.cpp',
    'MimeType.cpp',
    'Node.cpp',
    'NodeInfo.cpp',
    'NodeMonitor.cpp',
    # 'NodeMonitorHandler.cpp',
    'OffsetFile.cpp',
    'Path.cpp',
    'PathFinder.cpp',
    'PathMonitor.cpp',
    'Query.cpp',
    'QueryPredicate.cpp',
    'ResourceFile.cpp',
    'ResourceItem.cpp',
    'ResourcesContainer.cpp',
    'Resources.cpp',
    'ResourceStrings.cpp',
    'Statable.cpp',
    'storage_support.cpp',
    'SymLink.cpp',
    'Volume.cpp',
    'VolumeRoster.cpp',
]

srcs_storage = files(srcs_storage)