linux_desktop_entry_install_script = meson.project_source_root() + '/src/apps/desktop/install_linux_desktop_entry.sh'
mimeset_install_script = meson.project_source_root() + '/src/apps/install_with_mimeset.sh'

subdir('aboutsystem')
subdir('clock')
subdir('charactermap')
subdir('columns')
subdir('deskbar')
subdir('deskcalc')
subdir('diskusage')
subdir('fontdemo')
subdir('gradients')
subdir('showcase')
subdir('gui-torture')
subdir('icon-o-matic')
subdir('mandelbrot')
subdir('minimal')
subdir('minimal-noui')
subdir('minitracker')
subdir('msgtest')
subdir('pairs')
subdir('pulse')
subdir('resedit')
subdir('showimage')
subdir('stylededit')
subdir('sudoku')
subdir('terminal')
