subdir('aboutsystem')
subdir('clock')
subdir('deskcalc')
subdir('diskusage')
subdir('fontdemo')
subdir('gradients')
subdir('guido')
subdir('icon-o-matic')
subdir('mandelbrot')
subdir('minimal')
subdir('minimal-noui')
subdir('pairs')
subdir('resedit')
subdir('showimage')
subdir('stylededit')
subdir('sudoku')
subdir('terminal')