srcs_wayland = [
    'protocol/wlr-foreign-toplevel-management-unstable-v1-protocol.c',
    'protocol/wlr-layer-shell-unstable-v1-protocol.c',
    'protocol/tablet-unstable-v2-protocol.c',
    'protocol/color-management-v1-protocol.c',
    'protocol/viewporter-protocol.c',
    'protocol/relative-pointer-unstable-v1-protocol.c',
    'protocol/xdg-shell-protocol.c',
    'protocol/text-cursor-position-protocol.c',
    'protocol/pointer-constraints-unstable-v1-protocol.c',
    'clients/window.c',
    'shared/image-loader.c',
    'shared/os-compatibility.c',
    'shared/matrix.c',
    'shared/cairo-util.c',
    'shared/file-util.c',
    'shared/frame.c',
]

srcs_wayland = files(srcs_wayland)