executable(
	'Benchmark',
	[
		'Benchmark.cpp',
		'DrawingModeToString.cpp',
		'HorizontalLineTest.cpp',
		'RandomLineTest.cpp',
		'StringTest.cpp',
		'Test.cpp',
		'TestWindow.cpp',
		'VerticalLineTest.cpp',
	],
	dependencies: [dep_libroot],
	include_directories: common_inc,
	link_with: lib_libbe,
	install: false,
)