srcs_support = [
    'Archivable.cpp',
    'ArchivingManagers.cpp',
    'Beep.cpp',
    'BlockCache.cpp',
    'BufferedDataIO.cpp',
    'BufferIO.cpp',
    'ByteOrder.cpp',
    'DataIO.cpp',
    'DateTime.cpp',
    'Flattenable.cpp',
    'Job.cpp',
    'JobQueue.cpp',
    'List.cpp',
    'Locker.cpp',
    'PointerList.cpp',
    'Referenceable.cpp',
    'StopWatch.cpp',
    'String.cpp',
    'StringList.cpp',
    'Uuid.cpp',
]

# Add Windows-specific helper files
if is_windows
    srcs_support += ['string_helper.cpp']
endif

srcs_support = files(srcs_support)