#pragma once

#define DATADIR "/usr/local/share"

#define HAVE_BUILTIN_BSWAP32 1
#define HAVE_BUILTIN_CLZ 1
#define HAVE_BUILTIN_POPCOUNT 1
#define HAVE_MEMFD_CREATE 1
#define HAVE_MKOSTEMP 1
#define HAVE_PANGO 1
#define HAVE_POSIX_FALLOCATE 1
#define HAVE_STRCHRNUL 1
#define HAVE_UNREACHABLE 1
#define HAVE_WEBP 1
#define HAVE_XKBCOMMON_COMPOSE 1
#define USE_RESIZE_POOL 1

#define _ALL_SOURCE 1

#define _GNU_SOURCE 1

