
srcs_mapm = [
    'mapm5sin.c',
    'mapm_add.c',
    'mapmasin.c',
    'mapmasn0.c',
    'mapmcbrt.c',
    'mapmcnst.c',
    'mapm_cpi.c',
    'mapm_div.c',
    'mapm_exp.c',
    'mapmfact.c',
    'mapm_fam.c',
    'mapm_fft.c',
    'mapm_flr.c',
    'mapmfmul.c',
    'mapm_fpf.c',
    'mapm_gcd.c',
    'mapmgues.c',
    'mapmhasn.c',
    'mapmhsin.c',
    'mapmipwr.c',
    'mapmistr.c',
    'mapm_lg2.c',
    'mapm_lg3.c',
    'mapm_lg4.c',
    'mapm_log.c',
    'mapm_mul.c',
    'mapm_pow.c',
    'mapmpwr2.c',
    'mapm_rcp.c',
    'mapm_rnd.c',
    'mapmrsin.c',
    'mapm_set.c',
    'mapm_sin.c',
    'mapmsqrt.c',
    'mapmstck.c',
    'mapmutil.c',
    'mapmutl1.c',
    'mapmutl2.c',
]

lib_libmapm = static_library(
    'mapm',
    srcs_mapm,
    include_directories: include_directories(['.', '../../../headers/libs/mapm']),
    c_args: ['-O2'],
    install: false,
)

dep_libmapm = declare_dependency(
    link_with: lib_libmapm,
    include_directories: include_directories('.'),
)