iconomatic_includes = [
    'document',
    'document/savers',
    'generic',
    'generic/listener',
    'generic/support',
    'generic/command',
    'generic/gui',
    'generic/gui/panel',
    'generic/gui/panel/color_picker',
    'generic/gui/scrollview',
    'generic/gui/stateview',
    'generic/property',
    'generic/property/specific_properties/',
    'generic/property/view',
    'generic/property/view/specific_properties',
    'generic/selection',
    'generic/property/view/specific_properties',
    'transformable',
    'gui',
    'import_export',
    'import_export/bitmap',
    'import_export/flat_icon',
    'import_export/message',
    'import_export/styled_text',
    'import_export/svg',
    'shape',
    'shape/commands',
    'style',
]

srcs_iconomatic = [
    'main.cpp',
    'MainWindow.cpp',
    'Util.cpp',
    'IconEditorApp.cpp',
    'CanvasView.cpp',
    'document/Document.cpp',
    'document/IconObject.cpp',
    'document/SetPropertiesCommand.cpp',
    'document/savers/AttributeSaver.cpp',
    'document/savers/BitmapSetSaver.cpp',
    'document/savers/DocumentSaver.cpp',
    'document/savers/MessengerSaver.cpp',
    'document/savers/FileSaver.cpp',
    'document/savers/NativeSaver.cpp',
    'document/savers/SimpleFileSaver.cpp',
    'MainWindow.cpp',
    'style/AssignStyleCommand.cpp',
    'style/CurrentColor.cpp',
    'style/MoveStylesCommand.cpp',
    'style/SetColorCommand.cpp',
    'style/AddStylesCommand.cpp',
    'style/RemoveStylesCommand.cpp',
    'style/SetGradientCommand.cpp',
    'generic/command/Command.cpp',
    'generic/command/CommandStack.cpp',
    'generic/command/CompoundCommand.cpp',
    'generic/support/support_settings.cpp',
    'generic/support/Debug.cpp',
    'generic/support/support_ui.cpp',
    'generic/support/support.cpp',
    'generic/listener/Observer.cpp',
    'generic/listener/Observable.cpp',
    'generic/listener/AbstractLOAdapter.cpp',
    'generic/gui/stateview/Manipulator.cpp',
    'generic/gui/stateview/ViewState.cpp',
    'generic/gui/stateview/MultipleManipulatorState.cpp',
    'generic/gui/stateview/StateView.cpp',
    'generic/gui/Group.cpp',
    'generic/gui/NummericalTextView.cpp',
    'generic/gui/InputTextView.cpp',
    'generic/gui/ListViews.cpp',
    #'generic/gui/IconOptionsControl.cpp',
    'generic/gui/SwatchView.cpp',
    'generic/gui/StringTextView.cpp',
    'generic/gui/panel/Panel.cpp',
    'generic/gui/panel/color_picker/ColorPickerPanel.cpp',
    'generic/gui/panel/color_picker/AlphaSlider.cpp',
    'generic/gui/panel/color_picker/ColorSlider.cpp',
    'generic/gui/panel/color_picker/ColorPickerView.cpp',
    'generic/gui/panel/color_picker/ColorField.cpp',
    'generic/gui/panel/color_picker/ColorPreview.cpp',
    # 'generic/gui/popup_control/InputSlider.cpp',
    # 'generic/gui/popup_control/PopupSlider.cpp',
    # 'generic/gui/popup_control/PopupWindow.cpp',
    # 'generic/gui/popup_control/PopupControl.cpp',
    # 'generic/gui/popup_control/PopupView.cpp',
    # 'generic/gui/popup_control/SliderView.cpp',
    'generic/gui/scrollview/Scroller.cpp',
    'generic/gui/scrollview/ScrollableView.cpp',
    'generic/gui/scrollview/ScrollView.cpp',
    'generic/gui/scrollview/Scrollable.cpp',
    'generic/selection/Selectable.cpp',
    'generic/selection/Selection.cpp',
    'generic/property/CommonPropertyIDs.cpp',
    'generic/property/Property.cpp',
    'generic/property/view/PropertyItemView.cpp',
    'generic/property/view/PropertyListView.cpp',
    'generic/property/view/PropertyEditorFactory.cpp',
    'generic/property/view/PropertyEditorView.cpp',
    'generic/property/view/specific_properties/StringValueView.cpp',
    'generic/property/view/specific_properties/ColorValueView.cpp',
    'generic/property/view/specific_properties/BoolValueView.cpp',
    'generic/property/view/specific_properties/TextInputValueView.cpp',
    'generic/property/view/specific_properties/FloatValueView.cpp',
    'generic/property/view/specific_properties/OptionValueView.cpp',
    'generic/property/view/specific_properties/IconValueView.cpp',
    'generic/property/view/specific_properties/IntValueView.cpp',
    'generic/property/view/specific_properties/Int64ValueView.cpp',
    'generic/property/view/specific_properties/SwatchValueView.cpp',
    'generic/property/PropertyObject.cpp',
    'generic/property/specific_properties/Int64Property.cpp',
    'generic/property/specific_properties/IconProperty.cpp',
    'generic/property/specific_properties/OptionProperty.cpp',
    'generic/property/specific_properties/ColorProperty.cpp',
    'shape/PathManipulator.cpp',
    'shape/commands/MoveShapesCommand.cpp',
    'shape/commands/ChangePointCommand.cpp',
    'shape/commands/ReversePathCommand.cpp',
    'shape/commands/RotatePathIndicesCommand.cpp',
    'shape/commands/SplitPointsCommand.cpp',
    'shape/commands/RemovePointsCommand.cpp',
    'shape/commands/InsertPointCommand.cpp',
    'shape/commands/AddPointCommand.cpp',
    'shape/commands/AddTransformersCommand.cpp',
    'shape/commands/MovePathsCommand.cpp',
    'shape/commands/CleanUpPathCommand.cpp',
    'shape/commands/PathCommand.cpp',
    'shape/commands/RemovePathsCommand.cpp',
    'shape/commands/TransformPointsCommand.cpp',
    'shape/commands/RemoveTransformersCommand.cpp',
    'shape/commands/AddShapesCommand.cpp',
    'shape/commands/UnassignPathCommand.cpp',
    'shape/commands/AddPathsCommand.cpp',
    'shape/commands/NudgePointsCommand.cpp',
    'shape/commands/FreezeTransformationCommand.cpp',
    'shape/commands/RemoveShapesCommand.cpp',
    'shape/commands/MoveTransformersCommand.cpp',
    'shape/commands/FlipPointsCommand.cpp',
    'import_export/svg/DocumentBuilder.cpp',
    'import_export/svg/SVGExporter.cpp',
    'import_export/svg/SVGImporter.cpp',
    'import_export/bitmap/BitmapExporter.cpp',
    'import_export/Exporter.cpp',
    'import_export/Importer.cpp',
    'import_export/flat_icon/SourceExporter.cpp',
    'import_export/flat_icon/FlatIconExporter.cpp',
    'import_export/flat_icon/RDefExporter.cpp',
    'import_export/message/MessageExporter.cpp',
    'import_export/styled_text/StyledTextImporter.cpp',
    'gui/IconView.cpp',
    'gui/PathListView.cpp',
    'gui/GradientControl.cpp',
    'gui/StyleView.cpp',
    'gui/IconObjectListView.cpp',
    'gui/StyleListView.cpp',
    'gui/ShapeListView.cpp',
    'gui/SwatchGroup.cpp',
    'gui/SavePanel.cpp',
    'gui/TransformerListView.cpp',
    'transformable/TransformObjectsCommand.cpp',
    'transformable/PerspectiveBoxStates.cpp',
    'transformable/ResetTransformationCommand.cpp',
    'transformable/TransformGradientCommand.cpp',
    'transformable/TransformShapesBox.cpp',
    'transformable/PerspectiveBox.cpp',
    'transformable/TransformCommand.cpp',
    'transformable/CanvasTransformBox.cpp',
    'transformable/TransformPointsBox.cpp',
    'transformable/PerspectiveCommand.cpp',
    'transformable/TransformBox.cpp',
    'transformable/TransformGradientBox.cpp',
    'transformable/ChannelTransform.cpp',
    'transformable/TransformBoxStates.cpp',
]


iconomatic_app = executable(
    'Icon-O-Matic',
    srcs_iconomatic,
    cpp_args: [
        '-DICON_O_MATIC=1',
        '-D__HAIKU__'
    ],
    link_with: [
        lib_libicon_iconomatic,
        lib_libbe,
        lib_libtracker,
    ],
    dependencies: [
        dep_libbe,
        dep_libtracker,
        dep_libicon_iconomatic
    ],
    include_directories: [
        icon_inc,
        common_inc,
        iconomatic_includes,
    ],
    install: true,
    link_args: is_windows ? ['-Wl,--disable-stdcall-fixup', '-Wl,--enable-auto-import', '-Wl,--no-insert-timestamp', '-static-libgcc', '-static-libstdc++', '-lmsvcrt'] : [],
    gui_app: is_windows,
)

srcs_iconomatic_resources = [
    'Icon-O-Matic.rdef'
]

iconomatic_resources = custom_target('iconomatic resources',
    depends : [iconomatic_app, rc_app],
    input : srcs_iconomatic_resources,
    output : 'Icon-O-Matic.rsrc',
    command : [rc_app, '@INPUT@', '-o', '@OUTPUT@', '-I', '.'],
    build_by_default : true)

custom_target('iconomatic plus resources',
    depends : iconomatic_resources,
    input : iconomatic_app,
    output : 'fake',
    command : [xres_app, '-o', '@INPUT@', iconomatic_resources],
    build_by_default : true)