app_name = 'ResEdit'
linux_desktop_id = 'x-vnd.Haiku-ResEdit'
linux_desktop_categories = 'Development;Utility;'

app_srcs = files(
    'App.cpp',
    'BitmapView.cpp',
    'ImageEditor.cpp',
    'MiscEditors.cpp',
    'NumberEditors.cpp',
    'PreviewColumn.cpp',
    'ResFields.cpp',
    'ResListView.cpp',
    'ResourceData.cpp',
    'ResourceRoster.cpp',
    'ResView.cpp',
    'ResWindow.cpp',
)

app_dependencies = [dep_libbe, dep_libtracker]
app_include_directories = common_inc
