executable(
	'cursor_test',
	'CursorTest.cpp',
	dependencies: [dep_libroot],
	include_directories: [common_inc, '../bitmap_drawing'],
	link_with: lib_libbe,
	install: false,
)

executable(
	'cursor_bitmap_test',
	'CursorBitmapTest.cpp',
	dependencies: [dep_libroot],
	include_directories: [common_inc, '../bitmap_drawing'],
	link_with: lib_libbe,
	install: false,
)