app_name = 'DeskCalc'
linux_desktop_id = 'x-vnd.Haiku-DeskCalc'
linux_desktop_categories = 'Calculator;Utility;'

app_srcs = files(
    'CalcApplication.cpp',
    'CalcOptions.cpp',
    'CalcView.cpp',
    'CalcWindow.cpp',
    'DeskCalc.cpp',
    'ExpressionTextView.cpp',
    'InputTextView.cpp',
)

app_resource_defs = files(
    app_name + '.rdef'
)

app_dependencies = dep_libbe
app_include_directories = common_inc
