install_data('develop/makefile-engine', install_dir : '/usr/local/etc')

# Required for our Wayland windowframe
install_data('artwork/icon_window.png', install_dir : '/usr/local/share/cosmoe')
install_data('artwork/sign_close.png', install_dir : '/usr/local/share/cosmoe')
install_data('artwork/sign_maximize.png', install_dir : '/usr/local/share/cosmoe')
install_data('artwork/sign_minimize.png', install_dir : '/usr/local/share/cosmoe')