app_name = 'FontDemo'
linux_desktop_id = 'x-vnd.Haiku-FontDemo'
linux_desktop_categories = 'Graphics;Utility;'

app_srcs = files(
    'ControlView.cpp',
    'FontDemo.cpp',
    'FontDemoView.cpp',
)

app_resource_defs = files(
    app_name + '.rdef'
)

app_link_with = [lib_libbe]
app_dependencies = [dep_libbe]
app_include_directories = common_inc
