app_name = 'MiniTracker'
linux_desktop_id = 'x-vnd.Cosmoe-MiniTracker'
linux_desktop_categories = 'System;FileManager;Utility;'

app_srcs = files(
    'app.cpp',
	'MiniTrackerApp.cpp'
)

app_resource_defs = files(
    app_name + '.rdef'
)

app_dependencies = [dep_libbe, dep_libtracker]
app_include_directories = common_inc
