srcs_shared = [
    'BitmapButton.cpp',
    # 'CalendarView.cpp',
    'ColorItem.cpp',
    'DragTrackingFilter.cpp',
    'ExpressionParser.cpp',
    'HashString.cpp',
    'HSL.cpp',
    'Keymap.cpp',
    'LongAndDragTrackingFilter.cpp',
    'NaturalCompare.cpp',
    'SettingsHandler.cpp',
    'StatusView.cpp',
    'StringForSize.cpp',
    'Thread.cpp',
    'ToolBar.cpp',
]

srcs_shared = files(srcs_shared)
