app_name = 'Columns'
linux_desktop_id = 'x-vnd.Cosmoe-Columns'
linux_desktop_categories = 'Game;BoardGame;'

app_srcs = files(
    'diswindow.cpp',
    'disapp.cpp',
    'app.cpp'
)

app_resource_defs = files(
    app_name + '.rdef'
)

app_dependencies = [dep_libbe, dep_libtracker]
app_include_directories = [common_inc, tracker_inc]
