NAME = msgtest
TYPE = APP
SRCS =	diswindow.cpp \
	app.cpp \
	disapp.cpp
LIBS =	be tracker

DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)

include $(DEVEL_DIRECTORY)/etc/makefile-engine