app_name = 'ShowImage'
linux_desktop_id = 'x-vnd.Haiku-ShowImage'
linux_desktop_categories = 'Graphics;Viewer;'

app_srcs = files(
    'Filter.cpp',
    'ImageCache.cpp',
    'ImageFileNavigator.cpp',
	'InfoStatusView.cpp',
    'PrintOptionsWindow.cpp',
	'ProgressStatusView.cpp',
    'ShowImageApp.cpp',
    'ShowImageSettings.cpp',
    'ShowImageStatusView.cpp',
    'ShowImageView.cpp',
    'ShowImageWindow.cpp',
    'SupportingAppsMenu.cpp',
    'ToolBarIcons.cpp',
    'SelectionBox.cpp',
)


app_resource_defs = files(
    app_name + '.rdef'
)

app_dependencies = [dep_libbe, dep_libtracker]
